//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarningWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageData
    {
        public string imageName { get; set; }
        public string imageText { get; set; }
    }
}
