//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarningWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdraw
    {
        public int id { get; set; }
        public int UserID { get; set; }
        public string phone { get; set; }
        public int amount { get; set; }
        public System.DateTime date { get; set; }
    }
}
